### ISSUE TITLE
Documentation suggestions

### ISSUE THREAD

**Issue by flyingbarron** [GregAlt/SolarFinish#1]
1. Add a license file (MIT, Apache, whatever) so it's more clear to people about sharing/reusing your code.
2. Since you're making frequent improvements, add a version number to the code, so one can see when running with command -h or -v whether the most recent version is running.
3. It's not clear whether the code at https://colab.research.google.com/drive/1eNe_3cofDGsOkqKuQvgoWBhKUpQjagl4?usp=sharing is at the same version/level as the github code - please clarify

**Comment by GregAlt** [comment]
I addressed 1 and 2. For 3 - in general, I haven't been updating the colab version. But I just updated it now and verified it works. At some point I will discontinue colab support. For the moment though, with the version in the code at the top, you can verify which version it is.
